x-environment: &php-env
  environment:
    - APP_NAME=Laravel
    - APP_ENV=local
    - APP_DEBUG=true
    - DB_HOST=psgc-db
    - DB_DATABASE=psgc_api
    - DB_USERNAME=psgc_user
    - DB_PASSWORD=password
    - DB_PREFIX=psgc_
version: '3.7'
services:
  psgc-api:
    <<: *php-env
    build:
      context: .
    image: psgc-api
    volumes:
      - ./app:/var/www/html:rw
    depends_on:
      psgc-db:
        condition: service_healthy
    restart: unless-stopped
    ports:
      - 9095:80
  psgc-db:
    image: mysql/mysql-server:latest
    init: true
    environment:
      - MYSQL_DATABASE=psgc_api
      - MYSQL_USER=psgc_user
      - MYSQL_PORT=3306
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
    volumes:
      - db:/var/lib/mysql:rw
    command: --default-authentication-plugin=mysql_native_password --sql_mode=NO_ENGINE_SUBSTITUTION
volumes:
  db:
